import type { ComponentProps } from "react";
import type { Ionicons } from "@expo/vector-icons";

type IoniconsName = ComponentProps<typeof Ionicons>["name"];

export const AppIcons = {
  back: "chevron-back" as IoniconsName,
  forward: "chevron-forward" as IoniconsName,
  close: "close" as IoniconsName,
  closeCircle: "close-circle" as IoniconsName,
  chevronDown: "chevron-down" as IoniconsName,
  chevronUp: "chevron-up" as IoniconsName,

  delete: "trash-outline" as IoniconsName,
  edit: "create-outline" as IoniconsName,
  share: "share-outline" as IoniconsName,
  search: "search-outline" as IoniconsName,
  menu: "ellipsis-vertical" as IoniconsName,
  refresh: "refresh-outline" as IoniconsName,
  add: "add-circle-outline" as IoniconsName,
  send: "send-outline" as IoniconsName,

  checkmark: "checkmark-outline" as IoniconsName,
  checkmarkCircle: "checkmark-circle-outline" as IoniconsName,
  checkmarkDone: "checkmark-done-outline" as IoniconsName,
  alert: "alert-circle-outline" as IoniconsName,
  warning: "warning-outline" as IoniconsName,
  time: "time-outline" as IoniconsName,
  info: "information-circle-outline" as IoniconsName,

  heart: "heart-outline" as IoniconsName,
  heartActive: "heart" as IoniconsName,
  star: "star-outline" as IoniconsName,
  starActive: "star" as IoniconsName,
  eye: "eye-outline" as IoniconsName,
  eyeOff: "eye-off-outline" as IoniconsName,
  camera: "camera-outline" as IoniconsName,
  images: "images-outline" as IoniconsName,
  bookmark: "bookmark-outline" as IoniconsName,

  archive: "archive-outline" as IoniconsName,
  sold: "checkmark-circle-outline" as IoniconsName,
  bump: "arrow-up-outline" as IoniconsName,
  bumpCircle: "arrow-up-circle-outline" as IoniconsName,
  promote: "flash-outline" as IoniconsName,
  pro: "diamond-outline" as IoniconsName,
  car: "car-outline" as IoniconsName,
  carSport: "car-sport-outline" as IoniconsName,
  document: "document-text-outline" as IoniconsName,

  settings: "settings-outline" as IoniconsName,
  notifications: "notifications-outline" as IoniconsName,
  person: "person-outline" as IoniconsName,
  people: "people-outline" as IoniconsName,
  login: "log-in-outline" as IoniconsName,
  logout: "log-out-outline" as IoniconsName,

  compare: "git-compare-outline" as IoniconsName,
  flag: "flag-outline" as IoniconsName,
  ban: "ban-outline" as IoniconsName,
  freeze: "snow-outline" as IoniconsName,
  lock: "lock-closed-outline" as IoniconsName,
  calendar: "calendar-outline" as IoniconsName,
  location: "location-outline" as IoniconsName,
  verified: "checkmark-circle" as IoniconsName,
  shield: "shield-checkmark-outline" as IoniconsName,
  key: "key-outline" as IoniconsName,
  trophy: "trophy-outline" as IoniconsName,
  briefcase: "briefcase-outline" as IoniconsName,
  wallet: "wallet-outline" as IoniconsName,
  call: "call-outline" as IoniconsName,
  chatBubble: "chatbubble-ellipses-outline" as IoniconsName,
  storefront: "storefront-outline" as IoniconsName,
  globe: "globe-outline" as IoniconsName,
  gift: "gift-outline" as IoniconsName,
  card: "card-outline" as IoniconsName,
  pricetag: "pricetag-outline" as IoniconsName,
  pricetags: "pricetags-outline" as IoniconsName,
  receipt: "receipt-outline" as IoniconsName,
  swap: "swap-horizontal-outline" as IoniconsName,
  speedometer: "speedometer-outline" as IoniconsName,
  scale: "scale-outline" as IoniconsName,
  analytics: "analytics-outline" as IoniconsName,
  newspaper: "newspaper-outline" as IoniconsName,
  videocam: "videocam-outline" as IoniconsName,
  navigate: "navigate-outline" as IoniconsName,
  mail: "mail-outline" as IoniconsName,
  hourglass: "hourglass-outline" as IoniconsName,
  fingerprint: "finger-print-outline" as IoniconsName,
  headset: "headset-outline" as IoniconsName,
  sync: "sync-outline" as IoniconsName,
  openExternal: "open-outline" as IoniconsName,
  folderOpen: "folder-open-outline" as IoniconsName,
  image: "image-outline" as IoniconsName,
  barbell: "barbell-outline" as IoniconsName,
  flame: "flame-outline" as IoniconsName,
  business: "business-outline" as IoniconsName,
  options: "options-outline" as IoniconsName,
} as const;
