import { EQUIPMENT_OPTIONS } from "@/types/car";
import { translate } from "@/lib/i18n";

export const DB_OPTION_LABELS: Record<string, string> = {
  "12v_socket": "Розетка 12V",
  "14_inch_wheels": "Диски 14\"",
  "15_inch_wheels": "Диски 15\"",
  "16_inch_wheels": "Диски 16\"",
  "17_inch_wheels": "Диски 17\"",
  "18_inch_wheels": "Диски 18\"",
  "19_inch_wheels": "Диски 19\"",
  "20_inch_wheels": "Диски 20\"",
  "21_inch_wheels": "Диски 21\"",
  "22_inch_wheels": "Диски 22\"",
  "23_inch_wheels": "Диски 23\"",
  "24_inch_wheels": "Диски 24\"",
  "220v_socket": "Розетка 220V",
  "360_camera": "Камера 360\u00B0",
  abs: "ABS",
  activ_suspension: "Активная подвеска",
  adaptive_light: "Адаптивное освещение",
  adj_pedals: "Регулируемые педали",
  air_suspension: "Пневмоподвеска",
  airbag_curtain: "Шторки безопасности",
  airbag_driver: "Подушка водителя",
  airbag_passenger: "Подушка пассажира",
  airbag_rear_side: "Боковые задние подушки",
  airbag_side: "Боковые подушки",
  alarm: "Сигнализация",
  alcantara: "Алькантара",
  android_auto: "Android Auto",
  apple_carplay: "Apple CarPlay",
  aroma: "Ароматизация салона",
  ashtray_and_cigarette_lighter: "Пепельница и прикуриватель",
  asr: "Антипробуксовочная (ASR)",
  athermal_glass: "Атермальное остекление",
  audiopreparation: "Аудиоподготовка",
  audiosystem_cd: "CD-аудиосистема",
  audiosystem_tv: "ТВ-аудиосистема",
  auto_cruise: "Адаптивный круиз-контроль",
  auto_dimming_mirror: "Автозатемняющееся зеркало",
  auto_mirrors: "Складывание зеркал",
  auto_park: "Автоматическая парковка",
  automatic_lighting_control: "Автоматическое управление светом",
  aux: "AUX",
  bas: "Усилитель экстренного торможения (BAS)",
  black_roof: "Чёрная крыша",
  blind_spot: "Мониторинг слепых зон",
  bluetooth: "Bluetooth",
  body_kit: "Обвес кузова",
  body_mouldings: "Молдинги кузова",
  cap_seats_rear: "Чехлы задних сидений",
  central_airbag: "Центральная подушка",
  clean_air: "Система очистки воздуха",
  climate_control_1: "Климат-контроль 1-зонный",
  climate_control_2: "Климат-контроль 2-зонный",
  collision_prevention_assist: "Предотвращение столкновений",
  combo_interior: "Комбинированный салон",
  computer: "Бортовой компьютер",
  condition: "Кондиционер",
  cooling_box: "Холодильник",
  cruise_control: "Круиз-контроль",
  decorative_interior_lighting: "Декоративная подсветка салона",
  dha: "Автоматический дальний свет",
  digital_mirror: "Цифровое зеркало",
  door_sill_panel: "Накладки на пороги",
  drive_mode_sys: "Система выбора режима движения",
  driver_seat_electric: "Электропривод сиденья водителя",
  driver_seat_memory: "Память сиденья водителя",
  driver_seat_support: "Поясничная опора водителя",
  driver_seat_updown: "Регулировка сиденья водителя по высоте",
  drl: "Дневные ходовые огни",
  drowsy_driver_alert_system: "Датчик усталости водителя",
  duo_body_color: "Двухцветный кузов",
  e_adjustment_wheel: "Электрорегулировка руля",
  easy_trunk_opening: "Открытие багажника без рук",
  electro_mirrors: "Электрозеркала",
  electro_rear_seat: "Электропривод задних сидений",
  electro_trunk: "Электропривод багажника",
  electro_window_back: "Электростеклоподъёмники задние",
  electro_window_front: "Электростеклоподъёмники передние",
  electronic_gage_panel: "Электронная приборная панель",
  entertainment_system_for_rear_seat_passengers: "Развлекательная система для задних пассажиров",
  esp: "Система стабилизации (ESP)",
  fabric_seats: "Тканевый салон",
  fcw: "Предупреждение о столкновении",
  feedback_alarm: "Обратная связь сигнализации",
  folding_front_passenger_seat: "Складное сиденье переднего пассажира",
  folding_tables_rear: "Столики для задних пассажиров",
  follow_me_home: "Провожающий свет",
  front_camera: "Камера переднего вида",
  front_centre_armrest: "Передний центральный подлокотник",
  front_seat_support: "Поясничная опора передних сидений",
  front_seats_heat: "Подогрев передних сидений",
  front_seats_heat_vent: "Вентиляция передних сидений",
  glonass: "ЭРА-ГЛОНАСС",
  hatch: "Люк в крыше",
  hcc: "Автоматическое управление климатом",
  heated_wash_system: "Обогрев системы омывания",
  high_beam_assist: "Ассистент дальнего света",
  immo: "Иммобилайзер",
  isofix: "Крепление Isofix",
  isofix_front: "Isofix на переднем сиденье",
  keyless_entry: "Бесключевой доступ",
  knee_airbag: "Подушка коленей водителя",
  knee_airbag_pass: "Подушка коленей пассажира",
  laminated_safety_glass: "Ламинированное стекло",
  lane_keeping_assist: "Удержание в полосе",
  laser_lights: "Лазерные фары",
  ldw: "Предупреждение о выезде из полосы",
  leather: "Кожаный салон",
  leather_gear_stick: "Кожаный рычаг КПП",
  led_lights: "Светодиодные фары",
  lidar: "Лидар",
  light_cleaner: "Омыватель фар",
  light_sensor: "Датчик света",
  lock: "Центральный замок",
  massage_seats: "Массаж сидений",
  mirrors_heat: "Подогрев зеркал",
  mirrors_memory: "Память зеркал",
  multi_wheel: "Мультифункциональный руль",
  multizone_climate_control: "Многозонный климат-контроль",
  music_super: "Премиум-аудиосистема",
  navigation: "Навигация",
  night_vision: "Ночное видение",
  paint_metallic: "Металлик",
  panorama_roof: "Панорамная крыша",
  park_assist_f: "Парктроник передний",
  park_assist_r: "Парктроник задний",
  passenger_seat_electric: "Электропривод сиденья пассажира",
  passenger_seat_updown: "Регулировка сиденья пассажира по высоте",
  pedestrian_detection: "Обнаружение пешеходов",
  power_child_locks_rear_doors: "Блокировка задних дверей",
  power_latching_doors: "Доводчики дверей",
  programmed_block_heater: "Программируемый предпусковой подогрев",
  projection_display: "Проекционный дисплей",
  ptf: "Противотуманные фары",
  rain_sensor: "Датчик дождя",
  rcta: "Контроль пересечения траектории",
  rear_armrest: "Задний подлокотник",
  rear_camera: "Камера заднего вида",
  rear_seat_heat_vent: "Вентиляция задних сидений",
  rear_seat_memory: "Память задних сидений",
  rear_seats_heat: "Подогрев задних сидений",
  rec: "Видеорегистратор",
  reduce_spare_wheel: "Докатка",
  remote_car_services: "Удалённые сервисы",
  remote_engine_start: "Дистанционный запуск",
  roller_blind_for_rear_window: "Шторка заднего стекла",
  roller_blinds_for_rear_side_windows: "Шторки задних боковых стёкол",
  roof_rails: "Рейлинги на крыше",
  seat_memory: "Память сидений",
  seat_transformation: "Трансформация сидений",
  servo: "Усилитель руля",
  spare_wheel: "Запасное колесо",
  sport_pedals: "Спортивные педали",
  sport_seats: "Спортивные сиденья",
  sport_suspension: "Спортивная подвеска",
  start_button: "Кнопка запуска",
  start_stop_function: "Система старт-стоп",
  steel_wheels: "Стальные диски",
  steering_wheel_gear_shift_paddles: "Подрулевые переключатели",
  third_rear_headrest: "Третий задний подголовник",
  third_row_seats: "Третий ряд сидений",
  tinted_glass: "Тонировка стёкол",
  tja: "Ассистент движения в пробке",
  traffic_sign_recognition: "Распознавание дорожных знаков",
  tyre_pressure: "Контроль давления в шинах",
  usb: "USB",
  velvet_seats: "Велюровый салон",
  voice_recognition: "Голосовое управление",
  volume_sensor: "Датчик объёма (охрана)",
  vsm: "Стабилизация рулевого управления (VSM)",
  wheel_configuration1: "Конфигурация дисков 1",
  wheel_configuration2: "Конфигурация дисков 2",
  wheel_heat: "Подогрев руля",
  wheel_leather: "Кожаный руль",
  wheel_memory: "Память руля",
  wheel_power: "Электроусилитель руля",
  windcleaner_heat: "Обогрев форсунок омывателя",
  windscreen_heat: "Обогрев лобового стекла",
  wireless_charger: "Беспроводная зарядка",
  xenon: "Ксеноновые фары",
  ya_auto: "Яндекс.Авто",
};

export function translateOptionCode(code: string): string {
  const key = `options.${code}`;
  const translated = translate(key);
  return translated !== key ? translated : DB_OPTION_LABELS[code] || code.replace(/_/g, " ");
}

export const getEquipmentLabel = translateOptionCode;

export const DB_BODY_TYPE_MAP: Record<string, string> = {
  SEDAN: "sedan",
  SEDAN_2_DOORS: "sedan",
  SEDAN_HARDTOP: "sedan",
  HATCHBACK_3_DOORS: "hatchback_3d",
  HATCHBACK_4_DOORS: "hatchback_4d",
  HATCHBACK_5_DOORS: "hatchback_5d",
  LIFTBACK: "liftback",
  ALLROAD_3_DOORS: "suv_3d",
  ALLROAD_5_DOORS: "suv_5d",
  ALLROAD_OPEN: "suv_open",
  WAGON_3_DOORS: "wagon",
  WAGON_5_DOORS: "wagon",
  COUPE: "coupe",
  COUPE_HARDTOP: "coupe",
  CABRIO: "convertible",
  MINIVAN: "minivan",
  COMPACTVAN: "compactvan",
  MICROVAN: "microvan",
  PICKUP_ONE: "pickup",
  PICKUP_TWO: "pickup",
  PICKUP_ONE_HALF: "pickup",
  ROADSTER: "roadster",
  TARGA: "targa",
  FASTBACK: "fastback",
  SPEEDSTER: "convertible",
  LIMOUSINE: "limousine",
  VAN: "van",
  PHAETON: "convertible",
  PHAETON_WAGON: "wagon",
};

export function getEquipmentCategory(eq: string): string {
  const opt = EQUIPMENT_OPTIONS.find((o) => o.value === eq);
  return opt?.category || "other";
}
