import type { ApiListing, Car } from "@/types/car";
import { resolveMediaUri } from "@/lib/media";

function resolveImages(images: string[]): string[] {
  return images.map((img) => resolveMediaUri(img) || img);
}

export function mapListingToCar(listing: ApiListing): Car {
  return {
    id: String(listing.id),
    userId: listing.userId || undefined,
    vehicleType: listing.vehicleType || "passenger",
    brand: listing.brand,
    model: listing.model,
    generation: listing.generation,
    modificationId: listing.modificationId,
    configurationId: listing.configurationId,
    year: listing.year,
    price: listing.price,
    originalPrice: listing.originalPrice ?? null,
    creditDiscount: listing.creditDiscount ?? null,
    tradeInDiscount: listing.tradeInDiscount ?? null,
    insuranceDiscount: listing.insuranceDiscount ?? null,
    currency: listing.currency || "USD",
    mileage: listing.mileage,
    bodyType: listing.bodyType,
    fuelType: listing.fuelType,
    transmission: listing.transmission,
    driveType: listing.driveType,
    engineVolume: listing.engineVolume,
    horsepower: listing.horsepower,
    color: listing.color,
    images: resolveImages(listing.images || []),
    videoUrl: listing.videoUrl || null,
    exchangeDetails: listing.exchangeDetails || null,
    description: listing.description || "",
    location: listing.location || "",
    sellerName: listing.sellerName || "",
    sellerPhone: listing.sellerPhone || "",
    sellerType: listing.sellerType || "private",
    bumpedAt: listing.bumpedAt || null,
    createdAt: listing.createdAt || new Date().toISOString(),
    isFavorite: listing.isFavorite || false,
    condition: listing.condition || "used",
    hasPhotos: (listing.images || []).length > 0,
    steeringWheel: listing.steeringWheel || "left",
    hasGasEquipment: listing.hasGasEquipment ?? false,
    exchangePossible: listing.exchangePossible ?? false,
    installmentPossible: listing.installmentPossible ?? false,
    installmentDetails: listing.installmentDetails || null,
    creditAvailable: listing.creditAvailable ?? false,
    tradeInAvailable: listing.tradeInAvailable ?? false,
    tradeInMaxAge: listing.tradeInMaxAge ?? null,
    tradeInBonus: listing.tradeInBonus ?? null,
    ownersCount: listing.ownersCount || 1,
    equipment: listing.equipment || [],
    trimName: listing.trimName || undefined,
    importCountry: listing.importCountry,
    accidentHistory: listing.accidentHistory || "none",
    bodyDamages: listing.bodyDamages || undefined,
    lastServiceDate: listing.lastServiceDate,
    keysCount: listing.keysCount || 1,
    warranty: listing.warranty,
    availability: listing.availability || "in_stock",
    vin: listing.vin,
    vinStatus: listing.vinStatus,
    noLegalIssues: listing.noLegalIssues,
    acceleration: listing.acceleration,
    fuelConsumption: listing.fuelConsumption,
    groundClearance: listing.groundClearance,
    trunkVolume: listing.trunkVolume,
    characteristics: listing.characteristics || [],
    payloadCapacity: listing.payloadCapacity,
    axleCount: listing.axleCount,
    cabinType: listing.cabinType,
    wheelConfiguration: listing.wheelConfiguration,
    grossWeight: listing.grossWeight,
    seatingCapacity: listing.seatingCapacity,
    coolingType: listing.coolingType,
    cylinderCount: listing.cylinderCount,
    operatingHours: listing.operatingHours,
    chassisType: listing.chassisType,
    operatingWeight: listing.operatingWeight,
    seatHeight: listing.seatHeight,
    dryWeight: listing.dryWeight,
    fuelTankCapacity: listing.fuelTankCapacity,
    bucketVolume: listing.bucketVolume,
    diggingDepth: listing.diggingDepth,
    boomLength: listing.boomLength,
    bladeWidth: listing.bladeWidth,
    tractionClass: listing.tractionClass,
    liftingCapacity: listing.liftingCapacity,
    liftingHeight: listing.liftingHeight,
    drumVolume: listing.drumVolume,
    rollerWidth: listing.rollerWidth,
    cuttingWidth: listing.cuttingWidth,
    hasPTO: listing.hasPTO,
    drillingDepth: listing.drillingDepth,
    pavingWidth: listing.pavingWidth,
    platformCapacity: listing.platformCapacity,
    views: listing.views ?? 0,
    status: listing.status ?? "active",
    moderationNote: listing.moderationNote ?? null,
    isGoodOffer: listing.isGoodOffer ?? false,
    avgMarketPrice: listing.avgMarketPrice,
    previousPrice: listing.previousPrice,
    promotion: listing.promotion ?? null,
    isProSeller: listing.isProSeller ?? false,
    dealerPlanCode: listing.dealerPlanCode ?? null,
    dealerRating: listing.dealerRating ?? null,
    dealerReviewCount: listing.dealerReviewCount ?? null,
    dealerCompanyName: listing.dealerCompanyName ?? null,
    sellerAvatarUrl: listing.sellerAvatarUrl ?? null,
    sellerCompanyLogoUrl: listing.sellerCompanyLogoUrl ?? null,
    sellerCompanyName: listing.sellerCompanyName ?? null,
    sellerShowroomAddress: listing.sellerShowroomAddress ?? null,
    sellerCity: listing.sellerCity ?? null,
    creditMinDownPaymentPercent: listing.creditMinDownPaymentPercent ?? null,
    creditInterestRateFrom: listing.creditInterestRateFrom ?? null,
    creditMaxMonths: listing.creditMaxMonths ?? null,
    creditPartnerBankIds: listing.creditPartnerBankIds ?? null,
    estimatedMonthlyFrom: listing.estimatedMonthlyFrom ?? null,
    creditBanks: listing.creditBanks ?? null,
  };
}
