export {
  getVehicleLabel,
  getBodyTypeLabel,
  getFuelTypeLabel,
  getTransmissionLabel,
  getDriveTypeLabel,
  getConditionLabel,
  getSteeringWheelLabel,
  getVehicleTypeLabel,
  getAvailabilityLabel,
  getOwnersCountLabel,
  getAccidentHistoryLabel,
  getImportCountryLabel,
  getSellerTypeLabel,
  getCabinTypeLabel,
  getChassisTypeLabel,
  getSuspensionTypeLabel,
  getCoolingTypeLabel,
  getMotoDriveTypeLabel,
  getCharacteristicLabel,
  getColorHex,
  getColorLabel,
} from "./vehicle-config/vehicle-labels";
